export const THEAD = [
  "#",
  "Update",
  "Achtenaam",
  "Voornaam",
  "Saldo",
  "Social",
  "Kind Geboortedatum",
  "School",
  "Level",
  "Straatnaam en huisnummer",
  "PostCode",
  "Gemeente",
  "Contact1",
  "Tel:1",
  "Contact2",
  "Tel:2",
  "Ouder RN",
  "Ouder Geboortedatum",
  "Kind RN",
  "Email",
  "Allergieën",
  "Opmerkingen ouders",
  "Opmerkingen pleinleiding",
  "Medische Fiche",
  "Week 1",
  "Week 2",
  "Week 3",
  "Week 4",
  ""
];
